export const VACANCY_SEED_DATA = [
  {
    legacyId: 'sm-cashier',
    title: 'Supermarket Cashier (Part Time)',
    department: 'Supermarket',
    employmentType: 'Part Time',
    status: 'Active',
    location: 'Hilversum, Netherlands',
    workingDays: 'Monday – Saturday',
    workingHours: '08:00 AM – 10:00 PM',
    cvRequired: true,
    closingDate: new Date('2025-07-15'),
    icon: 'cashier',
    summary:
      'Provide friendly checkout service, handle payments accurately, and create a welcoming experience for every customer.',
    description:
      'We are looking for a reliable cashier to support daily supermarket operations. You will assist customers at checkout, maintain a tidy counter area, and work closely with the front-end team during busy periods.',
    createdAt: new Date('2025-06-10'),
  },
  {
    legacyId: 'sm-stock',
    title: 'Stock & Shelf Assistant',
    department: 'Supermarket',
    employmentType: 'Full Time',
    status: 'Active',
    location: 'Hilversum, Netherlands',
    workingDays: 'Monday – Saturday',
    workingHours: '07:00 AM – 04:00 PM',
    cvRequired: false,
    closingDate: new Date('2025-07-20'),
    icon: 'stock',
    summary:
      'Keep shelves fully stocked, rotated, and labelled while maintaining excellent store presentation.',
    description:
      'Join our supermarket operations team to receive deliveries, replenish shelves, and help maintain a well-organised shopping environment for customers.',
    createdAt: new Date('2025-06-05'),
  },
  {
    legacyId: 'sm-produce',
    title: 'Fresh Produce Specialist',
    department: 'Supermarket',
    employmentType: 'Full Time',
    status: 'Active',
    location: 'Hilversum, Netherlands',
    workingDays: 'Monday – Saturday',
    workingHours: '06:00 AM – 02:00 PM',
    closingDate: new Date('2025-07-10'),
    icon: 'produce',
    summary:
      'Maintain vibrant fresh produce displays and advise customers on quality fruits and vegetables.',
    description:
      'Play a key role in our fresh department by preparing displays, checking quality, and helping customers choose the best produce for their needs.',
    createdAt: new Date('2025-05-28'),
  },
  {
    legacyId: 'fc-chef',
    title: 'Food Corner Chef / Kitchen Staff',
    department: 'Food Corner',
    employmentType: 'Full Time',
    status: 'Active',
    location: 'Hilversum, Netherlands',
    workingDays: 'Wednesday – Sunday',
    workingHours: '02:00 PM – 10:00 PM',
    closingDate: new Date('2025-07-25'),
    icon: 'chef',
    summary:
      'Prepare authentic Indian and Sri Lankan dishes including biryani, kottu roti, noodles, and daily specials.',
    description:
      'We are looking for an experienced Food Corner Chef / Kitchen Staff member to prepare fresh meals for our takeaway customers.',
    createdAt: new Date('2025-06-12'),
  },
  {
    legacyId: 'fc-cashier',
    title: 'Food Corner Cashier',
    department: 'Food Corner',
    employmentType: 'Part Time',
    status: 'Active',
    location: 'Hilversum, Netherlands',
    workingDays: 'Friday – Sunday',
    workingHours: '04:00 PM – 10:00 PM',
    closingDate: new Date('2025-07-18'),
    icon: 'cashier',
    summary: 'Handle food corner orders, payments, and customer service at the counter.',
    description:
      'Support our food corner team by taking orders, processing payments, and ensuring every customer receives quick and friendly service.',
    createdAt: new Date('2025-06-08'),
  },
  {
    legacyId: 'fc-service',
    title: 'Food Corner Service Crew',
    department: 'Food Corner',
    employmentType: 'Part Time',
    status: 'Active',
    location: 'Hilversum, Netherlands',
    workingDays: 'Thursday – Sunday',
    workingHours: '05:00 PM – 11:00 PM',
    closingDate: new Date('2025-07-12'),
    icon: 'service',
    summary: 'Serve customers, maintain dining area standards, and support counter operations.',
    description:
      'Join our service crew to deliver warm hospitality, assist with meal packaging, and keep the food corner service area clean and welcoming.',
    createdAt: new Date('2025-06-02'),
  },
  {
    legacyId: 'fc-counter',
    title: 'Food Corner Counter Staff',
    department: 'Food Corner',
    employmentType: 'Full Time',
    status: 'Active',
    location: 'Hilversum, Netherlands',
    workingDays: 'Wednesday – Sunday',
    workingHours: '11:00 AM – 11:00 PM',
    closingDate: new Date('2025-07-08'),
    icon: 'counter',
    summary: 'Manage food counter operations, customer orders, and daily service routines.',
    description:
      'Work at the heart of our food corner by handling customer orders, coordinating with kitchen staff, and maintaining excellent service standards throughout the day.',
    createdAt: new Date('2025-05-30'),
  },
  {
    legacyId: 'fc-trainee',
    title: 'Store Assistant Supervisor Trainee',
    department: 'Food Corner',
    employmentType: 'Full Time',
    status: 'Active',
    location: 'Hilversum, Netherlands',
    workingDays: 'Monday – Saturday',
    workingHours: '09:00 AM – 06:00 PM',
    closingDate: new Date('2025-06-30'),
    icon: 'trainee',
    summary: 'Train to support store and food corner supervision with leadership development.',
    description:
      'An excellent opportunity for motivated candidates to learn supermarket and food corner operations while developing supervisory skills under experienced team leaders.',
    createdAt: new Date('2025-05-22'),
  },
];
